author: "Riccardo Granchi <riccardo.granchi at nems.it"
category: "data"
summary: "ZeroPush Module"
home: "http://nems.it/ejabberd/mod_zero_push"
url: "riccardo.granchi@nems.it:ejabberd/mod_zero_push.git"
