author: "Riccardo Granchi <riccardo.granchi at nems.it"
category: "http"
summary: "ZeroPush Module"
home: "https://bitbucket.org/nems/mod_zeropush/src/master/"
url: "/opt/ejabberd/.ejabberd-modules/sources/mod_zeropush.zip"
