author: "Riccardo Granchi <riccardo.granchi at nems.it"
category: "http"
summary: "ZeroPush Module"
home: "https://bitbucket.org/nems/mod_zeropush/src/master/"
url: "https://granchir@github.com/granchir/mod_zeropush.git"
